lookarr:
  language: en-us
  strict_mode_allowed_ids: [ ]
  search_all_command: search

radarr:
  enabled: True
  url: 0.0.0.0
  port: 7878
  defaults:
    quality_profile: Any
    path:

sonarr:
  enabled: True
  url: 0.0.0.0
  port: 8989
  defaults:
    quality_profile: Any
    path: