name: _build

on:
  workflow_call:


jobs:

  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: ./scripts/test.sh

      - name: Build Package
        run: ./scripts/build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lookarr
          path: ./dist/*