name: Python package

on: [push]

permissions:
  contents: write

jobs:

  build:
    uses: ./.github/workflows/_build.yml

  push:
    needs: [ build ]
    uses: ./.github/workflows/_push.yml
    secrets: inherit