name: push_docker

on:
  workflow_dispatch:

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: lookarr
          path: ./artifacts

      - name: Semantic versioning
        id: versioning
        uses: paulhatch/semantic-version@v5.2.1
        with:
          tag_prefix: "v"
          major_pattern: "breaking" 
          minor_pattern: "feat"
          version_format: "v${major}.${minor}.${patch}-prerelease${increment}"

      - name: Set Tag
        id: tag
        run: |
          if ${{ github.ref_name == github.event.repository.default_branch }}
          then
            echo "tag=${{ steps.versioning.outputs.version_tag }}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ steps.versioning.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - id: ref
        shell: bash
        run: echo "refspec=${{ github.sha }}" >> $GITHUB_OUTPUT


      - name: Zip Release
        run: |
          mkdir release
          zip -r ./release/lookarr.${{ steps.tag.outputs.tag }}.zip ./artifacts/*

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          allowUpdates: true
          artifacts: ./release/lookarr.${{ steps.tag.outputs.tag }}.zip
          prerelease: ${{ github.ref_name != github.event.repository.default_branch }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.tag }}
          commit: ${{ steps.ref.outputs.refspec }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Docker Tags
        id: docker_tags
        run: |
          if ${{ github.ref_name == github.event.repository.default_branch }}
          then
            echo "docker_tags=${{ secrets.DOCKER_HUB_USERNAME }}/lookarr:${{ steps.tag.outputs.tag }}, ${{ secrets.DOCKER_HUB_USERNAME }}/lookarr:latest" >> $GITHUB_OUTPUT
          else
            echo "docker_tags=${{ secrets.DOCKER_HUB_USERNAME }}/lookarr:${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Push
        uses: docker/build-push-action@v4
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_tags.outputs.docker_tags }}